name: firjan_mercadolivre
recipe: drupal9
config:
  webroot: web
proxy:  
  appserver:    
    - firjan_mercadolivre.lndo.site    
services:
  firjan_mercadolivre:
    type: mysql:5.7    
    creds:      
      user: drupal9      
      password: drupal9      
      database: firjan_mercadolivre